### ISSUE TITLE
Primitive explorer

### ISSUE THREAD

**Issue by peterpan79** [DarkPhoenix10/windows93-js-docs#9]
What is the source code of the folders and files viewer? Its php json based? Please write it here! Thanks

**Comment by DarkPhoenix10** [comment]
sorry for the late reply, don't go on github much, but
the file explorer is written in javascript, iirc its source code is in https://windows93.net/c/sys42.js
unfortunately, everything in there is obfuscated
also, all the files and folder displayed in /c/ in the file explorer are in https://windows93.net/files.json
